### ISSUE TITLE
wc.nf script is missing?

### ISSUE THREAD

**Issue by tomsing1** [carpentries-incubator/workflows-nextflow#12]
The [first lesson](https://github.com/carpentries-incubator/workflows-nextflow/blob/gh-pages/_episodes/01-getting-started-with-nextflow.md#your-first-script) refers to a `wc.nf` script in the `scripts` folder:
> Open the file wc.nf in the script directory with your favourite text editor.

It seems this folder is not included in the material downloaded from Seqera. 

```bash
ls
data		env.yml		hello.nf	parsing		script3.nf	script6.nf
docs		exercises	mail.config	script1.nf	script4.nf	script7.nf
dsl2		hands-on	nextflow.config	script2.nf	script5.nf	setup
```
Perhaps it has moved? Or perhaps I misunderstood and learners are actually expected to *create* a `scripts` folder and the `wc.nf` script within it?

Thanks a ton for creating the nextflow training material, super useful!
Thomas

**Comment by tomsing1** [comment]
Ah, I think you might be in the process of changing the training datasets (see issue #3 ), and the `wc.nf` refers to the [new data](https://github.com/ggrimes/nextflow_rnaseq_training_dataset).  
Anyway, perhaps my commend about the missing `scripts` folder is still useful.

**Comment by ggrimes** [comment]
Hi @tomsing1 

Thanks for looking through my material this is super helpful.  I haven't worked out the best place to put the scripts and data for the exercises yet. I am also in the process of updating the material to include DSL2 from the beginning, so there will be more changes to come.

**Comment by ggrimes** [comment]
The files directory now contains all the scripts for the workshop
