### ISSUE TITLE
wc.nf script duplicates output lines

### ISSUE THREAD

**Issue by tomsing1** [carpentries-incubator/workflows-nextflow#13]
When I run the [wc.nf](https://github.com/carpentries-incubator/workflows-nextflow/blob/gh-pages/_episodes/01-getting-started-with-nextflow.md#your-first-script) script with the specified version of nextflow, the output (number of lines + filename) is duplicated:

```
nextflow run wc.nf
N E X T F L O W  ~  version 20.10.0
Launching `wc.nf` [goofy_hugle] - revision: 46c287748f
executor >  local (1)
[14/39d7d2] process > numLines (1) [100%] 1 of 1 ✔
    3628 ref1_1.fq.gz

    3628 ref1_1.fq.gz
```

When I rerun it after commenting out the `num_out.view()` line in the script, the output is only shown once:

```
nextflow run wc.nf
N E X T F L O W  ~  version 20.10.0
Launching `wc.nf` [kickass_stone] - revision: 0ccac4963b
executor >  local (1)
[51/c915be] process > numLines (1) [100%] 1 of 1 ✔
    3628 ref1_1.fq.gz
```

**Comment by ggrimes** [comment]
The contents of wc.nf file in episode has been changed and this will be fixed.
