### ISSUE TITLE
Clarify that directories should be searched recursively?

### ISSUE THREAD

**Issue by tomsing1** [carpentries-incubator/workflows-nextflow#14]
The [Channel glob exercise](https://github.com/carpentries-incubator/workflows-nextflow/blob/gh-pages/_episodes/03-channels.md#using-channelfrompath) currently reads:

> Use the Channel.fromPath method to create a channel containing all files in the data/yeast/ directory

It doesn't specify that files in the subdirectories should be listed as well. (I only realized that when I looked at the solution.) Perhaps add "recursively" to the task or - with less jargon - "including those in subdirectories" to the task's description?

**Comment by ggrimes** [comment]
Changed the exercise text to

```
Use the Channel.fromPath method to create a channel containing all files, including those in subdirectories, in the data/yeast/ directory.

Add an option, hidden, to include hidden files.

Then print all file names using the view operator.
```

and moved hint to question

`Hint: You need two asterisks, i.e. **, to search subdirectories.`
