### ISSUE TITLE
$basedir variable might need to be introduced

### ISSUE THREAD

**Issue by tomsing1** [carpentries-incubator/workflows-nextflow#16]
When the [publishDir directive is introduced](https://github.com/carpentries-incubator/workflows-nextflow/blob/ea0dcf55fbadf4c7f393f99e64b5daf59cadb78d/_episodes/04-processes.md#publishdir-directive) the `$basedir` variable is mentioned. Perhaps it would be useful to introduce it as well?

**Comment by ggrimes** [comment]
I will try and remove any references to `baseDir `in the lesson as it has been deprecated in favour of` projectDir` since 20.04.0

https://www.nextflow.io/docs/latest/script.html?highlight=basedir
