### ISSUE TITLE
Thoughts on Core vs Supplementary material

### ISSUE THREAD

**Issue by mahesh-panchal** [carpentries-incubator/workflows-nextflow#28]
What are your thoughts on the core curriculum and supplementary material?

Should nf-core be part of the core materials or a supplementary material?
There are a few episodes we could write on nf-core workflows.
- How to run an nf-core workflow (perhaps this should be core material?)
- How to use nf-core modules in your own workflow ( should this be supplementary, or is this beyond the scope of this lesson and we point to nf-core docs?)
- Including nf-core workflows in your workflow. (same thoughts as above)

**Comment by ggrimes** [comment]
I would like to include an introduction to nf-core episode as part of the core curriculum.
This would include how to find and run an nf-core pipeline using the test dataset.
This episode should include links to finding further information.
Episodes that include writing nf-core pipelines and using the modules systems could be supplementary or become part of a separate lesson.

**Comment by mahesh-panchal** [comment]
I'm beginning to think it would be better to have nf-core related tutorials on nf-core only so we don't have to maintain a second copy. However I do agree that we should at least include how to find and run an nf-core workflow. It's not easy figuring out if nf-core has a workflow for what one would like, and if it does what they want or stops part way. E.g. lots of people want differential expression too from rnaseq but it doesn't do it yet.

**Comment by mahesh-panchal** [comment]
I think there is a consensus here.
