### ISSUE TITLE
Add to channels about using `.out`

### ISSUE THREAD

**Issue by mahesh-panchal** [carpentries-incubator/workflows-nextflow#52]
The channels episode does not currently describe how to access channel outputs or the difference when `.out` should be used.
e.g.
```
workflow {
    index = INDEX( input_ch )
}
```
vs
```
workflow {
    INDEX( input_ch )
    index = INDEX.out
}
```

**Comment by ggrimes** [comment]
I cover this in the workflow episode.  Do you think it should be put in the channels episode?

**Comment by mahesh-panchal** [comment]
Hmm. Perhaps not then. It's a `workflow` specific concept.
