### ISSUE TITLE
Thoughts on the duration of training

### ISSUE THREAD

**Issue by kerimoff** [carpentries-incubator/workflows-nextflow#55]
We have completed the in-person training in Tartu on 22-23 November 2021.

This issue contains my thoughts on the timing of the whole course and for each individual episode:

First, per individual episode: 
**DAY 1**
- 01-getting-started-with-nextflow -> 23 mins
- 02-nextflow_scripting -> 1 hour 13 mins
- 03-workflow_parameters -> 30 minutes
- 04-channels -> 57 minutes
- 05-processes-part1 -> 1 hour 55 mins
- 05-processes-part2 ->  1 hour 45 mins
*====== (End of DAY 1) =======*
OVERALL DAY 1: ~400 minutes = 6 hours 40 minutes

**DAY 2**
> I switched the order of operators and workflow episodes because it makes more sense (e.g. we use collect operator in workflow episode which we learn in operators)
- 07-operators -> 1 hour 30 minutes
- 06-workflow -> 45 minutes
- 08-configuration -> 1 hour 30 minutes
- 09-Simple_Rna-Seq_pipeline -> 2 hour 10 minutes
- 10-Modules -> SKIPPED
- 11-subworkflows -> SKIPPED
- 12-reporting -> SKIPPED
- 13-workflow_checkpoint_caching -> 30 minutes
- 14-nfcore -> 40 minutes
*====== (End of DAY 2) =======*
OVERALL DAY 2: ~420 minutes = 7 hours

---

NOTES: 
* I waited for everyone to complete the exercises and not hurry them up.
* I did not skip almost any exercises (except the ones in nf-core episode, I demonstrated all myself)
* Attendees were happy with the pace of the training (not too fast, not too slow/boring)
* These timings are based on the material I have slightly changed from the original https://github.com/kerimoff/workflows-nextflow
* I am **completely** convinced that this training should be a 3-day training

That is how I would prefer it to do next time:
**DAY 1**
- 01-getting-started-with-nextflow -> 23 mins
- 02-nextflow_scripting -> 1 hour 13 mins
- 03-workflow_parameters -> 30 minutes
- 04-channels -> 57 minutes
- 07-operators -> 1 hour 30 minutes (adding some more operators and exercises + 20 minutes)
- Give some introduction to Processes (40 minutes may be)
*====== (End of DAY 1) =======*
OVERALL DAY 1: ~270 + 20 + 40 minutes  = 330 minutes = 5 hours 30 minutes

**DAY 2**
- 05-processes-part1 -> 1 hour 25 mins (since we did some introduction in DAY1)
- 05-processes-part2 ->  1 hour 45 mins
- 06-workflow -> 45 minutes
- 08-configuration -> 1 hour 30 minutes
- 13-workflow_checkpoint_caching -> 30 minutes
*====== (End of DAY 2) =======*
OVERALL DAY 2: ~360 minutes = 6 hours

**DAY 3**
- 09-Simple_Rna-Seq_pipeline -> 2 hour 10 minutes
- 10-Modules -> SKIPPED
- 11-subworkflows -> SKIPPED
- NEW EPISODE - Debugging pipelines
- 12-reporting -> SKIPPED
- 14-nfcore -> 1 hour 20 minutes (instead of 40)
*====== (End of DAY 3) =======*
OVERALL DAY 3: ~210 minutes + UNKNOWN for 3 skipped episodes + overall questions and discussion= 6 hours

**Comment by mahesh-panchal** [comment]
Can you make a pull request updating the times then please?
@ggrimes Can then confirm if the timings concur from his feedback too.

**Comment by kerimoff** [comment]
I can, however, I think it is better to also get @ggrimes timings after his training is finished. So we have at least a sample size of 2. I believe the timings will depend on the number of participants and the training environment (online or offline). Also, we should probably discuss the potentially "new" structure of the material, which can greatly influence these timings.
