### ISSUE TITLE
Explaining the tools-software we are going to use in exercises

### ISSUE THREAD

**Issue by kerimoff** [carpentries-incubator/workflows-nextflow#57]
Based on the learner feedback we got after the first training it may be a good idea to explain the tools-software we are using in the examples/exercises (e.g. samtools, salmon, multiqc, fastqc etc.) or since it is argued that Nextflow is not only designed for the use of bioinformaticians the examples/exercises should be replaced to use more general tools/software (e.g. bash commands)

I am more in favour of explaining the tools we are using currently in the pipeline. But, also accept that it is a valid argument and should be probably discussed here or via Slack.

**Comment by mahesh-panchal** [comment]
Related #54

**Comment by mahesh-panchal** [comment]
What was your setting here? Did it follow from the carpentries genomics workshop or purely stand-alone?
I agree it would be a nice enhancement to have a table on what the tools are for reference.

**Comment by ggrimes** [comment]
Where would be out this material?

**Comment by kerimoff** [comment]
> What was your setting here? Did it follow from the carpentries genomics workshop or purely stand-alone? I agree it would be a nice enhancement to have a table on what the tools are for reference.

Our training was purely stand-alone. But, in my opinion, we should expect the people who are attending this course also from other disciplines than genomics/bioinformatics. 
I followed my own fork which probably 98% the same with original https://kerimoff.github.io/workflows-nextflow/02-nextflow_scripting/index.html

**Comment by kerimoff** [comment]
> Where would be put this material?

I think it should be a :callout in the beginning of exercise/example where we use the tool for the first time. (e.g. describe what **salmon** is and how it is used in the beginning of Processes episode)

The other option is to explain all of them in the episode 1 very briefly
These are the only ones we need to explain IMO:
  - salmon=1.5
  - fastqc=0.11.5
  - multiqc
  - fastp=0.23.0
  - samtools

**Comment by mahesh-panchal** [comment]
I think it would be nice if we had a domain specific description at the top with a table of the tools and what they do. The first exercise could then be, with a pen and paper, draw how these tools are connected.
