### ISSUE TITLE
Add instructions for using Gitpod to learn Nextflow

### ISSUE THREAD

**Issue by mahesh-panchal** [carpentries-incubator/workflows-nextflow#68]
The course can use the nf-core Gitpod container which will spin up cloud based dev environment that has Nextflow, and nf-core preinstalled along with some other tools, including docker, mamba, and conda.
Learners have a browser based file editor and terminal in one to learn Nextflow.
Add notes to make a subdirectory in `/workspace`, otherwise it's not saved if the session goes idle. 
There are 16 cores to use, and some small amount of memory and diskspace.
It's able to run the test profile of some nf-core workflows ( using `-profile test,docker`).

**Comment by lescai** [comment]
this is a very interesting feature, although I haven't been used GitPod before. happy to contribute.
