### ISSUE TITLE
Typo in nfcore_config.png

### ISSUE THREAD

**Issue by tavareshugo** [carpentries-incubator/workflows-nextflow#98]
In [this image](https://github.com/carpentries-incubator/workflows-nextflow/blob/main/episodes/fig/nfcore_config.png) there is a typo in the config file path: 

`$HOME/.nextflow.config` should be `$HOME/.nextflow/config`

I'm not sure this image is being used anymore, but in any case might be good to fix it.

**Comment by ggrimes** [comment]
Thanks for spottingbthis. I will update the image.
